name: "⚙️ CI / GitOps improvement"
description: "Improve CI, GitOps, releases, automation"
labels: ["ci-gitops", "automation"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Resumen"
      placeholder: "Qué quieres mejorar y por qué"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: "Propuesta"
      placeholder: "Pasos / cambios concretos"
    validations:
      required: true
  - type: textarea
    id: risks
    attributes:
      label: "Riesgos / rollback"
      placeholder: "Cómo revertir si algo falla"
