name: "🎮 Learning Task"
description: "Create a guided Learning-by-Doing challenge"
labels: ["learning-task"]
body:
  - type: markdown
    attributes:
      value: |
        Define un reto práctico, con resultado verificable y criterios de aceptación.
  - type: input
    id: level
    attributes:
      label: "Nivel (1-4)"
      placeholder: "1 Explorador / 2 Constructor / 3 Ingeniero / 4 Cooperador"
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: "Objetivo del reto"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: "Criterios de aceptación"
      placeholder: "- [ ] ...
- [ ] ..."
    validations:
      required: true
  - type: textarea
    id: resources
    attributes:
      label: "Recursos / enlaces"
