version: "1.0"
views:
  - id: sector_hub_es
    locale: es
    path: docs/sectors/sector-hub.md
    audience:
      - public_sector
      - regulated_private
      - compliance_risk
    required_sections:
      - "Soluciones Sectoriales"
      - "Infraestructura Cognitiva · Soberanía Regulada"
      - "Sectores Estratégicos"
      - "Universidades e Investigación"
      - "Ayuntamientos y Territorios ITI"
      - "Banca y Finanzas Reguladas"
      - "Salud y hospitales"
      - "PYMES Multisector"
      - "Autónomos y Microequipos"
      - "Asesorías Legales y Fiscales"
      - "Administraciones Públicas"
      - "Cooperativas y Economía Social"
      - "Infraestructuras Críticas y Sectores Regulados"
      - "Trust Pack y Recursos"
    required_links:
      - "./universities.md"
      - "./municipalities-iti.md"
      - "./regulated-banking.md"
      - "./healthcare.md"
      - "./smbs.md"
      - "./freelancers.md"
      - "./advisory-firms.md"
      - "./public-administration.md"
      - "./cooperatives.md"
      - "./other-regulated.md"
      - "../trust/overview.md"
      - "../trust/security-compliance.md"
      - "../trust/deployment-models.md"
    required_labels:
      - domain-docs
      - level-stable
    narrative_contract:
      markers:
        - "Problema a resolver"
        - "Resultado esperado"
        - "Contexto y Audiencia"
        - "Valor e Impacto (90 días)"
      min_occurrences: 10
    taxonomy_bindings:
      domain: atlantyqa
      sector: smb_multisector

  - id: sector_hub_en
    locale: en
    path: docs/sectors/sector-hub.en.md
    audience:
      - public_sector
      - regulated_private
      - compliance_risk
    required_sections:
      - "Sector Solutions"
      - "Cognitive Infrastructure · Regulated Sovereignty"
      - "Strategic Sectors"
      - "Universities & Research"
      - "Municipalities & ITI Territories"
      - "Banking & Regulated Finance"
      - "Healthcare & Hospitals"
      - "SMBs & Enterprises"
      - "Freelancers & Micro-teams"
      - "Legal, Tax & Advisory"
      - "Public Administrations"
      - "Cooperatives & Social Economy"
      - "Critical Infrastructure & Regulated Sectors"
      - "Trust Pack & Resources"
    required_links:
      - "./universities.en.md"
      - "./municipalities-iti.en.md"
      - "./regulated-banking.en.md"
      - "./healthcare.en.md"
      - "./smbs.en.md"
      - "./freelancers.en.md"
      - "./advisory-firms.en.md"
      - "./public-administration.en.md"
      - "./cooperatives.en.md"
      - "./other-regulated.en.md"
      - "../trust/overview.en.md"
      - "../trust/security-compliance.en.md"
      - "../trust/deployment-models.en.md"
    required_labels:
      - domain-docs
      - level-stable
    narrative_contract:
      markers:
        - "The challenge"
        - "What you gain"
        - "Context & Audience"
        - "Value & Impact (90 days)"
      min_occurrences: 10
    taxonomy_bindings:
      domain: atlantyqa
      sector: smb_multisector

  - id: trust_overview_es
    locale: es
    path: docs/trust/overview.md
    audience:
      - compliance_risk
      - procurement
      - platform_ops
    required_sections:
      - "Confianza y Gobernanza"
      - "Contenido del Trust Pack"
    required_links:
      - "../sectors/sector-hub.md"
      - "../trust/security-compliance.md"
      - "../trust/deployment-models.md"
    required_labels:
      - domain-docs
    taxonomy_bindings:
      domain: coop_model
      sector: regulated_industry

  - id: trust_overview_en
    locale: en
    path: docs/trust/overview.en.md
    audience:
      - compliance_risk
      - procurement
      - platform_ops
    required_sections:
      - "Trust & Governance"
      - "Trust Pack Contents"
    required_links:
      - "../sectors/sector-hub.en.md"
      - "../trust/security-compliance.en.md"
      - "../trust/deployment-models.en.md"
    required_labels:
      - domain-docs
    taxonomy_bindings:
      domain: coop_model
      sector: regulated_industry

  - id: legal_privacy_es
    locale: es
    path: docs/legal/privacy.md
    audience:
      - legal
      - compliance_risk
    required_sections:
      - "Politica de Privacidad"
      - "Principios Clave"
    required_links:
      - "inno@atlantyqa.org"
    required_labels:
      - domain-docs
    taxonomy_bindings:
      domain: coop_model
      sector: regulated_industry

  - id: legal_privacy_en
    locale: en
    path: docs/legal/privacy.en.md
    audience:
      - legal
      - compliance_risk
    required_sections:
      - "Privacy Policy"
      - "Core Principles"
    required_links:
      - "inno@atlantyqa.org"
    required_labels:
      - domain-docs
    taxonomy_bindings:
      domain: coop_model
      sector: regulated_industry
